version: "3.7"

services:
  web:
    build: ./src
    command: gunicorn tm.wsgi:application --bind 0.0.0.0:5000 --reload
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./envs/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.dev.db

volumes:
  postgres_data:
  redis_data:
