# Generated by Django 3.1 on 2020-09-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0002_auto_20200927_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_event', to='event_crm.event', verbose_name='Блок мероприятия'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='registration_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='event_crm.registrationevent', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration_event', to='event_crm.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='event_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration_event', to='event_crm.eventparticipant', verbose_name='Участник мероприятия'),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='part_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration_event', to='event_crm.partevent', verbose_name='Блок'),
        ),
    ]
