# Generated by Django 3.1 on 2020-09-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0003_auto_20200927_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='part_event', to='event_crm.event', verbose_name='Блок мероприятия'),
        ),
    ]
