# Generated by Django 3.1 on 2020-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0004_auto_20200928_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='registrationevent',
            options={'verbose_name': 'Регистрация на мероприятие', 'verbose_name_plural': 'Регистрации на мероприятие'},
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала мероприятия'),
        ),
        migrations.AddField(
            model_name='partevent',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='partevent',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='partevent',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала мероприятия'),
        ),
    ]
