# Generated by Django 3.1 on 2020-10-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0005_auto_20201016_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='partevent',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='partevent',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала мероприятия'),
        ),
    ]
