# Generated by Django 3.1 on 2020-10-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0006_auto_20201016_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_event', related_query_name='part_event', to='event_crm.event', verbose_name='Мероприяте'),
        ),
    ]
