# Generated by Django 3.1 on 2020-10-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0008_partevent_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('курс НЛП практик', 'курс НЛП практик'), ('мастер класс', 'мастер класс'), ('тренинг', 'тренинг'), ('трансформационная игра', 'трансформационная игра'), ('Он-лайн мероприятие', 'Он-лайн мероприятие')], max_length=50, null=True, verbose_name='Тип мероприятия'),
        ),
    ]
