# Generated by Django 3.1 on 2020-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0009_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('курс НЛП практик', 'nlp_practic'), ('мастер класс', 'master_class'), ('тренинг', 'trening'), ('трансформационная игра', 'game'), ('Он-лайн мероприятие', 'on-line event')], max_length=50, null=True, verbose_name='Тип мероприятия'),
        ),
    ]
