# Generated by Django 3.1 on 2020-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0010_auto_20201019_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блока')),
            ],
            options={
                'verbose_name': 'Название блока',
                'verbose_name_plural': 'Название блоков',
            },
        ),
    ]
