# Generated by Django 3.1 on 2020-10-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0011_namepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='partevent',
            name='name_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_crm.namepart', verbose_name='Название блока'),
        ),
    ]
