# Generated by Django 3.1 on 2020-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_crm', '0012_partevent_name_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='namepart',
            name='name_plural',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название блоков'),
        ),
    ]
